### ISSUE TITLE
Install package requires parameter creation

### ISSUE THREAD

**Issue by jcdm** [DashMedia/GetIds#5]
Installer requires two system settings to be created for the snippet. These changes are to pair with the pull request #4 which needs these in place to function correctly.

Key: getids.depth
Name: Depth of search
Description: Integer value indicating depth to search for resources from each parent
Value: 10
Type: Textfield
Namespace: getids
Area Lexicon Entry: getids:default

Key: getids.subsample_size
Name: Default size of subsample
Description: Integer value indicating how many children to retrieve as a cross-section when the 's' parameter is used
Value: 10
Type: Textfield
Namespace: getids
Area Lexicon Entry: getids:default

**Comment by jonathanhaslett** [comment]
I've added these new system settings and lexicon entries to the repoman seeds.
